spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.HashMap

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  file:
    name: logs/myapp.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: INFO
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR